baseurl = "http://www.taralind.com/"
title = "TARA LIND"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "taralind"

[markup.highlight]
style = "github-dark"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Tara Lind"
  info = "Sports Data Science PhD Candidate"
  description = "Tara Lind's personal website"
  keywords = "blog,scientist,personal"
  avatarurl = "/TaraLindpic.jpg"
  #gravatar = "t.lind@latrobe.edu.au"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/taralind"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "www.linkedin.com/in/tara-lind"
[[params.social]]
  name = "La Trobe University"
  icon = "fa-solid fa-graduation-cap fa-2x"
  weight = 1
  url = "https://scholars.latrobe.edu.au/tlind"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Research"
  weight = 2
  url = "research/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
[[menu.main]]
  name = "Other"
  weight = 4
  url = "other/"